### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by hobbitronics** [arineng/cidr-calc#3]
When I install and use cidr-calc in a node module I get the following warning in the console:

`(!) Circular dependencies
node_modules/cidr-calc/lib/index.js -> node_modules/cidr-calc/lib/ip-notation-utils.js -> node_modules/cidr-calc/lib/index.js
node_modules/cidr-calc/lib/index.js -> node_modules/cidr-calc/lib/ip-parse-utils.js -> node_modules/cidr-calc/lib/index.js`

steps to reproduce:

1. create a project in svelte or other framework
2. import cidr-calc as described in the docs
`import { IpAddress, IpRange } from "cidr-calc";
const ipRange = new IpRange(IpAddress.of("0::0"), IpAddress.of("0::1"));
console.log(ipRange);`
3. Open your app and look in the console.

**Comment by hobbitronics** [comment]
It looks like because you are using `IPV4_BYTE_COUNT` and `IPV6_BYTE_COUNT` from `lib/index.js` in `ip-notation-utils.js` while also requiring `regularNotationV4`, `regularNotationV6`, and similar utils in in `lib/index.js` this warning is happening. I'm not sure it's worth it to you to move `IPV4_BYTE_COUNT` and `IPV6_BYTE_COUNT` to a separate module or not, but that should take care of the first warning.

**Comment by liangbodeng** [comment]
Thank you, @hobbitronics, for bringing this issue to our attention. We've made some code adjustments and released a new version, 1.0.4. Would you be able to give it a try and inform us if the problem persists? Your feedback is greatly appreciated.

**Comment by hobbitronics** [comment]
@liangbodeng Thanks so much for addressing this so quickly. I have updated and the warnings are gone. Great work!

**Comment by hobbitronics** [comment]
> When I install and use cidr-calc in a node module I get the following warning in the console:
> 
> `(!) Circular dependencies node_modules/cidr-calc/lib/index.js -> node_modules/cidr-calc/lib/ip-notation-utils.js -> node_modules/cidr-calc/lib/index.js node_modules/cidr-calc/lib/index.js -> node_modules/cidr-calc/lib/ip-parse-utils.js -> node_modules/cidr-calc/lib/index.js`
> 
> steps to reproduce:
> 
> 1. create a project in svelte or other framework
> 2. import cidr-calc as described in the docs
>    `import { IpAddress, IpRange } from "cidr-calc"; const ipRange = new IpRange(IpAddress.of("0::0"), IpAddress.of("0::1")); console.log(ipRange);`
> 3. Open your app and look in the console.

I didn't have time to get this working earlier but in case any related issues arise here's a stackblitz https://stackblitz.com/edit/simple-svelte-9hwfvr?file=src%2FApp.svelte
